### PR TITLE
Add clj-kondo lint config and address lint warnings

### PR DESCRIPTION
**Pull request by lread**
@weavejester, as discussed. 
As usual, happy to tweak.

### CODE REVIEW

**Comment by weavejester** [comment]
I've cherry-picked the fixes. I want to think about the clj-kondo integration.

**Comment by lread** [comment]
> I've cherry-picked the fixes. I want to think about the clj-kondo integration.

Fair enough @weavejester, ideally the clj-kondo lint config would exert your personal preferences.
When/if you become ready for clj-kondo, I am happy to help.
Feel free to close this PR but maybe we should leave issue #232 open?

**Comment by ericdallo** [comment]
IMO we should merge this PR :p

**Comment by lread** [comment]
> IMO we should merge this PR :)

I, of course, agree. I know that I prefer contributing to projects that have a clj-kondo config. 🙂

**Pull request closed without merging**
