### PR TITLE
Adding an Editor Support section

### PR DESCRIPTION
**Pull request by venantius**
Hopefully not too shameless, but adding a section on editor support for Vim.

### CODE REVIEW

**Comment by weavejester** [comment]
I think I'd prefer something briefer, like:

```
## Editor Support

* [vim-cljfmt](https://github.com/venantius/vim-cljfmt)
```

There's no need to clutter up the cljfmt README when people can just follow a link to the project page.

Also, could you ensure that the commit message describes the change in a little more detail? Like:

```
Update README with link to vim-cljfmt
```

**Comment by venantius** [comment]
Sure, no problem. Let me kill this and make a cleaner submission.

**Comment by weavejester** [comment]
You do know that you can change the contents of a pull request without closing it, right?

**Comment by venantius** [comment]
In point of fact, I did not.

**Comment by weavejester** [comment]
Most people don't seem to know that. Pull requests are bound to a branch name, but you can update the local branch through a `git rebase -i` or `git commit --amend` or a `git reset`, and then overwrite the remote branch with `git push -f`.

It's generally more useful to keep changes in one PR, as it keeps everything in one place.

**Comment by venantius** [comment]
Ah; I use `git commit --amend` all the time locally, but I've always avoided using it on any sort of remote repository because it hoses anybody else who was looking at it. I suppose for this use case, though, the harm of `git push -f` is about as minimal as possible.

**Pull request closed without merging**
