### PR TITLE
Add tests for keyword and alias namespaced maps

### PR DESCRIPTION
**Pull request by lread**
Relates to #125.

### CODE REVIEW

**Comment by lread** [comment]
Hmmm... good question. I don't see any specific advice in the [style guide](https://github.com/bbatsov/clojure-style-guide).  
[Clojure's own examples](https://clojure.org/guides/weird_characters#__code_code_and_code_code_namespace_map_syntax) show the `#:x{:a 1}` formatting. I assume that's where folks will learn about this feature and probably adopt the example syntax therein. 
Soo... maybe I need to tweak this one.

**Comment by danielcompton** [comment]
The Clojure printer prints it as `#:x{:a 1}`, so I'd say that is probably the better route to go down.

**Comment by weavejester** [comment]
Let's go with `#:x{:a 1}`, then, as the idiomatic formatting.

**Comment by weavejester** [comment]
I think so, though with the caveat that we add an option to turn the behavior off for those that want it.

**Comment by lread** [comment]
An option, because it needs a name, leads me to think about generalizing.

I wonder how many other similar syntaxes would fit into this category and what their current behaviors are. For examples:
1. Cljfmt  will reformat ``#_   (+ 1 2)`` to ``#_(+ 1 2)`` if `:remove-surrounding-whitespace` is `true`.
2. But, `#?      (:clj(+ 1 2))` is not affected.

**Comment by lread** [comment]
I should probably understand what these # syntaxes are commonly called.  

In our usage here it seems [# is the dispatch character](https://clojure.org/guides/weird_characters#dispatch).

So would we have `:remove-whitespace-after-dispatch?`?

(the focus of this pull request has totally changed from my original intent, I'll rename if we decide to continue - or if you prefer we could reject and move this to a new issue)

**Comment by weavejester** [comment]
That seems reasonable. Feel free to open a new PR and reference this one.

**Pull request closed without merging**
