### PR TITLE
Remove stacktrace workaround

### LINKED ISSUE #210: Workaround for clojure.stacktrace no longer needed for native-image
This was fixed in Clojure 1.10.2.

https://github.com/weavejester/cljfmt/blob/e75c430dab52c766828007a1ed32089419370134/cljfmt/src/cljfmt/impl/stacktrace.clj#L17

### PR DESCRIPTION
**Pull request by bsless**
Reflective access in clojure.stacktrace was cleaned up on Clojure 1.20.2.
By bumping the Clojure version this workaround can be safely removed

Closes #210

### CODE REVIEW

**Comment by weavejester** [comment]
Thanks for the PR!

> Addition of unsupported options reporting at runtime flag is to circumvent a
> reachable method via read-string which is used when reading a .clj file for the
> indents option.

Can you explain how this is connected to reflective access in `clojure.stacktrace`?

**Comment by bsless** [comment]
@weavejester It's actually not connected.
The unfortunate fact is that native-image building was not tested in subsequent PRs and one merge after it was added it got broken by the addition of `read-string` (#217). It was impossible to build a native mage without adding this flag first.
If you want to keep the repository's history clean I can reword the MR, commit message, or even split the MR.

**Comment by weavejester** [comment]
Could you split the PR, please. Ideally a commit should represent a single change to the codebase, and a PR should address a single problem.

**Comment by bsless** [comment]
Alright.
I'll get to it tomorrow because it's getting a bit late here.
Until then :)

**Comment by bsless** [comment]
Split to #219

**Comment by weavejester** [comment]
Thanks, and sorry for the delay in getting back to you. Everything looks good, but the commit message has a couple of small typos. Can you change the commit message to:

```
Remove clojure.stacktrace workaround

Reflective access in clojure.stacktrace was cleaned up in Clojure
1.10.2. By bumping the Clojure version this workaround can be safely
removed.
```

**Comment by bsless** [comment]
No worries, done :)

**Pull request merged**
